volumes:
  data:
services:
  amb01:
    container_name: moodleserver
    build: .
    ports:
    - "9090:80"
    - "9443:443"
    volumes:
    - ./moodledata/_data/:/var/www/moodledata
    links:
    - database

  database:
    image: mariadb:latest
    container_name: moodledb
    volumes:
    - ./mysql/_data/:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=myrootpass
    - MYSQL_DATABASE=moodle
    - MYSQL_USER=moodle_user
    - MYSQL_PASSWORD=mymoodlepass
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      links:
        - database
      ports:
        - 8088:80
      environment:
        - PMA_ARBITRARY=1
